// src/data.js

export const historicalEvents = [
  // Ancient History
  {
  id: "agriculture",
  era: "Ancient History",
  year: -10000,
  date: "c. 10,000 BCE",
  title: "The Agricultural Revolution",
  location: "Fertile Crescent",
  description: "Humans begin to transition from hunter-gatherer societies to settled agricultural communities, domesticating plants and animals.",
  link: "https://en.wikipedia.org/wiki/Neolithic_Revolution",
  icon: "fa-solid fa-wheat-awn",
  image: "https://www.ancient-origins.net/sites/default/files/field/image/Neolithic-revolution-ancient-farmers.jpg"
  },
  {
  id: "sumer",
  era: "Ancient History",
  year: -3500,
  date: "c. 3500 BCE",
  title: "The Rise of Sumer",
  location: "Mesopotamia",
  description: "The world's first civilization emerges, inventing writing (cuneiform), the wheel, and creating the first city-states like Uruk.",
  link: "https://en.wikipedia.org/wiki/Sumer",
  icon: "fa-solid fa-city",
  image: "https://www.realmofhistory.com/wp-content/uploads/2023/07/reconstruction-ur-city-sumerian_1-770x437.jpg"
  },
  {
  id: "indus-valley",
  era: "Ancient History",
  year: -3300,
  date: "c. 3300-1300 BCE",
  title: "Indus Valley Civilization",
  location: "Indus River Valley",
  description: "One of the world's first great urban civilizations, noted for its advanced urban planning, sophisticated water management systems, and a still-undeciphered script.",
  link: "https://en.wikipedia.org/wiki/Indus_Valley_Civilisation",
  icon: "fa-solid fa-building-columns",
  image: "https://miro.medium.com/1*wkI0YOZxviL2nM1UcwwGTg.jpeg"
  },
  {
  id: "pyramids",
  era: "Ancient History",
  year: -2560,
  date: "c. 2560 BCE",
  title: "Great Pyramid of Giza",
  location: "Giza, Egypt",
  description: "Completed as a tomb for Pharaoh Khufu, it's a masterpiece of ancient engineering and the only surviving wonder of the ancient world.",
  link: "https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza",
  icon: "fa-solid fa-landmark",
  image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pyramids_of_the_Giza_Necropolis.jpg/960px-Pyramids_of_the_Giza_Necropolis.jpg"
  },
  {
  id: "hammurabi",
  era: "Ancient History",
  year: -1780,
  date: "c. 1780 BCE",
  title: "Code of Hammurabi",
  location: "Babylon",
  description: "One of the earliest and most complete written legal codes, proclaimed by the Babylonian king Hammurabi.",
  link: "https://en.wikipedia.org/wiki/Code_of_Hammurabi",
  icon: "fa-solid fa-scale-balanced",
  image: "https://cdn.britannica.com/89/82589-050-98AA8FA9/Hammurabi-god-Babylon.jpg"
  },
  {
  id: "minoan-eruption",
  era: "Ancient History",
  year: -1600,
  date: "c. 1600 BCE",
  title: "Minoan Eruption of Thera",
  location: "Aegean Sea",
  description: "A catastrophic volcanic eruption on the island of Thera (modern Santorini) that devastated the Minoan civilization on Crete and had far-reaching consequences for the ancient world.",
  link: "https://en.wikipedia.org/wiki/Minoan_eruption",
  icon: "fa-solid fa-volcano",
  image: "https://i.natgeofe.com/n/6609fc9c-5145-4acb-a128-9c8136c49580/BAL_532073.jpg"
  },
  {
  id: "bronze-age-collapse",
  era: "Ancient History",
  year: -1200,
  date: "c. 1200 BCE",
  title: "Late Bronze Age Collapse",
  location: "Eastern Mediterranean",
  description: "A widespread societal collapse involving the decline of major civilizations like the Mycenaeans, Hittites, and parts of the Egyptian New Kingdom.",
  link: "https://en.wikipedia.org/wiki/Late_Bronze_Age_collapse",
  icon: "fa-solid fa-house-fire",
  image: "https://retrospectjournal.com/wp-content/uploads/2022/12/1024px-keuninck_coninck_kerstiaen_de_-_fire_of_troy.jpg?w=1024"
  },
  {
  id: "olympics",
  era: "Ancient History",
  year: -776,
  date: "c. 776 BCE",
  title: "First Olympic Games",
  location: "Olympia, Greece",
  description: "The ancient Olympic Games are founded, a festival of sport and culture that brought the Greek world together.",
  link: "https://en.wikipedia.org/wiki/Ancient_Olympic_Games",
  icon: "fa-solid fa-trophy",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUlQMIIp0EyeApaIHlMs9I_q1j86ALdfb1Bg&s"
  },
  // Classical Antiquity
  {
  id: "confucius",
  era: "Classical Antiquity",
  year: -551,
  date: "551-479 BCE",
  title: "Life of Confucius",
  location: "China",
  description: "The life of the influential Chinese philosopher Confucius, whose teachings on ethics, social order, and governance have profoundly shaped East Asian thought and culture.",
  link: "https://en.wikipedia.org/wiki/Confucius",
  icon: "fa-solid fa-scroll-old",
  image: "https://cdn.britannica.com/10/184710-050-D6503292/Confucius-Shanghai-China.jpg"
  },
  {
  id: "buddha",
  era: "Classical Antiquity",
  year: -500,
  date: "c. 5th Century BCE",
  title: "Life of the Buddha",
  location: "Ancient India",
  description: "Siddhartha Gautama achieves enlightenment, becoming the Buddha and founding Buddhism, a major world religion.",
  link: "https://en.wikipedia.org/wiki/The_Buddha",
  icon: "fa-solid fa-om",
  image: "https://www.vridhamma.org/sites/default/files/picture-bar/Life%20of%20the%20Buddha_1.jpg"
  },
  {
  id: "persian-wars",
  era: "Classical Antiquity",
  year: -499,
  date: "499-449 BCE",
  title: "The Persian Wars",
  location: "Greece and Persia",
  description: "A series of conflicts between the Achaemenid Empire of Persia and Greek city-states that resulted in a Greek victory and the preservation of Greek independence.",
  link: "https://en.wikipedia.org/wiki/Greco-Persian_Wars",
  icon: "fa-solid fa-swords",
  image: "https://i0.wp.com/the-past.com/wp-content/uploads/2021/09/post-1_image7-6.jpg?w=1230&ssl=1"
  },
  {
  id: "alexander",
  era: "Classical Antiquity",
  year: -334,
  date: "334-323 BCE",
  title: "Conquests of Alexander the Great",
  location: "Greece to India",
  description: "Alexander's military campaigns create one of the largest empires of the ancient world, spreading Greek culture across a vast area.",
  link: "https://en.wikipedia.org/wiki/Alexander_the_Great",
  icon: "fa-solid fa-horse",
  image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Alexander_the_Great_mosaic.jpg/1024px-Alexander_the_Great_mosaic.jpg"
  },
  {
  id: "mauryan-empire",
  era: "Classical Antiquity",
  year: -268,
  date: "c. 268-232 BCE",
  title: "Reign of Ashoka the Great",
  location: "Mauryan Empire, India",
  description: "The reign of Ashoka, the third emperor of the Mauryan Empire, who, after the bloody Kalinga War, converted to Buddhism and promoted its spread across Asia.",
  link: "https://en.wikipedia.org/wiki/Ashoka",
  icon: "fa-solid fa-lion",
  image: "https://kf-media-offload.s3.amazonaws.com/wp-content/uploads/2003/07/29122632/king-ashoka-of-india.jpg"
  },
  {
  id: "qin-dynasty",
  era: "Classical Antiquity",
  year: -221,
  date: "221 BCE",
  title: "Qin Shi Huang Unifies China",
  location: "China",
  description: "The end of the Warring States period marks the beginning of Imperial China. The Great Wall and Terracotta Army are constructed.",
  link: "https://en.wikipedia.org/wiki/Qin_Shi_Huang",
  icon: "fa-solid fa-dragon",
  image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/QinShiHuang19century.jpg/1200px-QinShiHuang19century.jpg"
  },
  {
  id: "punic-wars",
  era: "Classical Antiquity",
  year: -264,
  date: "264-146 BCE",
  title: "The Punic Wars",
  location: "Mediterranean",
  description: "A series of three wars fought between Rome and Carthage, resulting in the destruction of Carthage and the establishment of Roman dominance in the western Mediterranean.",
  link: "https://en.wikipedia.org/wiki/Punic_Wars",
  icon: "fa-solid fa-elephant",
  image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_2,w_3840,h_1920,g_auto/dpr_auto/f_auto/q_auto:eco/v1/gettyimages-534251372?_a=BAVAZGDX0"
  },
  {
  id: "augustus",
  era: "Classical Antiquity",
  year: -27,
  date: "27 BCE - 14 CE",
  title: "Reign of Augustus",
  location: "Roman Empire",
  description: "The reign of the first Roman Emperor, Augustus, marks the end of the Roman Republic and the beginning of the Pax Romana.",
  link: "https://en.wikipedia.org/wiki/Augustus",
  icon: "fa-solid fa-crown",
  image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_2,w_3840,h_1920,g_auto/dpr_auto/f_auto/q_auto:eco/v1/augustus-caesar-587488458?_a=BAVAZGDX0"
  },
  {
  id: "jesus",
  era: "Classical Antiquity",
  year: 30,
  date: "c. 30-33 CE",
  title: "Crucifixion of Jesus",
  location: "Jerusalem, Judea",
  description: "The execution of Jesus of Nazareth, a central event in Christianity, which forms the basis of the world's largest religion.",
  link: "https://en.wikipedia.org/wiki/Crucifixion_of_Jesus",
  icon: "fa-solid fa-cross",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-QIRmV2ALmJu4r_PQF_6RO42BCfX1r1ttJA&s"
  },
  // Post-Classical History
  {
  id: "fall-of-rome",
  era: "Post-Classical History",
  year: 476,
  date: "476 CE",
  title: "Fall of the Western Roman Empire",
  location: "Rome, Italy",
  description: "The deposition of the last emperor, Romulus Augustulus, by Odoacer is traditionally seen as the end of the Western Roman Empire.",
  link: "https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire",
  icon: "fa-solid fa-person-military-falling",
  image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,w_1200,h_630,g_auto/dpr_auto/f_auto/q_auto:eco/v1/gettyimages-802428712"
  },
  {
  id: "islam",
  era: "Post-Classical History",
  year: 610,
  date: "c. 610 CE",
  title: "The Revelations of Islam",
  location: "Mecca, Arabia",
  description: "The Prophet Muhammad begins receiving divine revelations, forming the basis of the Quran and the Islamic faith.",
  link: "https://en.wikipedia.org/wiki/Muhammad",
  icon: "fa-solid fa-moon",
  image: "https://mahadsunnah.com/wp-content/uploads/2022/11/347bc51242fe542208cc710cda9a87d0.webp"
  },
  {
  id: "islamic-golden-age",
  era: "Post-Classical History",
  year: 750,
  date: "c. 8th-14th Century",
  title: "Islamic Golden Age",
  location: "Middle East, North Africa, and Spain",
  description: "A period of cultural, economic, and scientific flourishing in the history of Islam, traditionally dated from the 8th century to the 14th century.",
  link: "https://en.wikipedia.org/wiki/Islamic_Golden_Age",
  icon: "fa-solid fa-star-and-crescent",
  image: "https://www.bibalex.org/SCIplanet/Attachments/Article/MediumImage/oMcJRNaWLQ_20220421123233316.jpg"
  },
  {
  id: "viking-age",
  era: "Post-Classical History",
  year: 793,
  date: "c. 793-1066",
  title: "The Viking Age",
  location: "Scandinavia and Northern Europe",
  description: "A period in European history, especially Northern European and Scandinavian history, following the Germanic Iron Age, when the Vikings undertook large-scale raiding, colonizing, conquest, and trading.",
  link: "https://en.wikipedia.org/wiki/Viking_Age",
  icon: "fa-solid fa-axe-battle",
  image: "https://cdn.shopify.com/s/files/1/0798/2432/2846/files/Harald-Hardrada_480x480.jpg?v=1723040282"
  },
  {
  id: "charlemagne",
  era: "Post-Classical History",
  year: 800,
  date: "800 CE",
  title: "Coronation of Charlemagne",
  location: "Rome, Italy",
  description: "Pope Leo III crowns Charlemagne as the first Holy Roman Emperor, uniting much of Western Europe for the first time since the Romans.",
  link: "https://en.wikipedia.org/wiki/Charlemagne",
  icon: "fa-solid fa-hat-wizard",
  image: "https://cdn.mos.cms.futurecdn.net/v2/t:0,l:525,cw:1350,ch:1350,q:80,w:1350/MRQBaH5S7udd5FQmKkbzTn.jpg"
  },
  {
  id: "great-schism",
  era: "Post-Classical History",
  year: 1054,
  date: "1054 CE",
  title: "The Great Schism",
  location: "Rome & Constantinople",
  description: "The formal split between the Western Roman Catholic and Eastern Orthodox churches, a division that persists to this day.",
  link: "https://en.wikipedia.org/wiki/East%E2%80%93West_Schism",
  icon: "fa-solid fa-people-arrows",
  image: "https://i.ytimg.com/vi/r73ixUECwHs/maxresdefault.jpg"
  },
  {
  id: "norman-conquest",
  era: "Post-Classical History",
  year: 1066,
  date: "1066",
  title: "Norman Conquest of England",
  location: "England",
  description: "The invasion and occupation of England by an army of Norman, Breton, and French soldiers led by Duke William II of Normandy, later styled William the Conqueror.",
  link: "https://en.wikipedia.org/wiki/Norman_conquest_of_England",
  icon: "fa-solid fa-castle",
  image: "https://www.english-heritage.org.uk/siteassets/home/00-shared-blocks-and-media/z-shared-blocks-and-media-archive/shared-media/william.jpg?w=550&h=350&mode=crop&scale=both&cache=always&quality=60&anchor=&WebsiteVersion=20200219"
  },
  {
  id: "crusades",
  era: "Post-Classical History",
  year: 1096,
  date: "1096-1291",
  title: "The Crusades",
  location: "Middle East",
  description: "A series of religious wars initiated, supported, and sometimes directed by the Latin Church in the medieval period, with the objective of recovering the Holy Land from Islamic rule.",
  link: "https://en.wikipedia.org/wiki/Crusades",
  icon: "fa-solid fa-shield-cross",
  image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_2,w_3840,h_1920,g_auto/dpr_auto/f_auto/q_auto:eco/v1/gettyimages-587492330?_a=BAVAZGDX0"
  },
  {
  id: "genghis-khan",
  era: "Post-Classical History",
  year: 1206,
  date: "1206",
  title: "Genghis Khan Unites the Mongols",
  location: "Central Asia",
  description: "Genghis Khan establishes the Mongol Empire, which would become the largest contiguous land empire in history.",
  link: "https://en.wikipedia.org/wiki/Genghis_Khan",
  icon: "fa-solid fa-horse-head",
  image: "https://media.newyorker.com/photos/65831f8b6186c093c0ab6968/16:9/w_2560,h_1440,c_limit/240101_r43571.jpg"
  },
  {
  id: "magna-carta",
  era: "Post-Classical History",
  year: 1215,
  date: "1215 CE",
  title: "Magna Carta Sealed",
  location: "Runnymede, England",
  description: "King John of England is forced to sign the 'Great Charter', a foundational document for constitutional law and individual liberties.",
  link: "https://en.wikipedia.org/wiki/Magna_Carta",
  icon: "fa-solid fa-scroll",
  image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg/800px-Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg"
  },
  {
  id: "marco-polo",
  era: "Post-Classical History",
  year: 1271,
  date: "1271-1295",
  title: "Travels of Marco Polo",
  location: "Asia",
  description: "The Venetian merchant Marco Polo's travels through Asia, which he chronicled in his book 'The Travels of Marco Polo,' providing Europeans with one of the first comprehensive looks into the East.",
  link: "https://en.wikipedia.org/wiki/The_Travels_of_Marco_Polo",
  icon: "fa-solid fa-map-marked-alt",
  image: "https://cdn.britannica.com/17/144417-050-53036450/Marco-Polo-travels-Asia-1271-1295.jpg"
  },
  {
  id: "mansa-musa",
  era: "Post-Classical History",
  year: 1324,
  date: "1324",
  title: "Mansa Musa's Pilgrimage to Mecca",
  location: "Mali Empire and Mecca",
  description: "The pilgrimage of Mansa Musa, the ruler of the wealthy Mali Empire, to Mecca, during which he spent so much gold that he caused a major economic inflation in the regions he passed through.",
  link: "https://en.wikipedia.org/wiki/Mansa_Musa",
  icon: "fa-solid fa-gold-ingot",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwdMmo02OylTbx3a8zQA693KoAll2hVWYmpA&s"
  },
  {
  id: "black-death",
  era: "Post-Classical History",
  year: 1347,
  date: "1347-1351 CE",
  title: "The Black Death",
  location: "Eurasia & North Africa",
  description: "One of the most devastating pandemics in human history, it resulted in the deaths of an estimated 75–200 million people.",
  link: "https://en.wikipedia.org/wiki/Black_Death",
  icon: "fa-solid fa-skull-crossbones",
  image: "https://www.historic-uk.com/wp-content/uploads/2017/06/black-death-2800x1440.jpg"
  },
  // Modern History
  {
  id: "renaissance",
  era: "Modern History",
  year: 1400,
  date: "c. 1400-1600",
  title: "The Renaissance",
  location: "Europe",
  description: "A fervent period of European cultural, artistic, political and economic 'rebirth' following the Middle Ages.",
  link: "https://en.wikipedia.org/wiki/Renaissance",
  icon: "fa-solid fa-palette",
  image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Leonardo_da_Vinci_%281452-1519%29_-_The_Last_Supper_%281495-1498%29.jpg/1280px-Leonardo_da_Vinci_%281452-1519%29_-_The_Last_Supper_%281495-1498%29.jpg"
  },
  {
  id: "printing-press",
  era: "Modern History",
  year: 1440,
  date: "c. 1440",
  title: "Invention of the Printing Press",
  location: "Mainz, Germany",
  description: "Johannes Gutenberg's invention of the printing press with movable type, which revolutionized the production of books and the dissemination of information.",
  link: "https://en.wikipedia.org/wiki/Printing_press",
  icon: "fa-solid fa-print",
  image: "https://cdn.britannica.com/43/120643-004-926C49EB/Illustration-Encyclopaedia-Britannica-printing-press-edition-stick.jpg"
  },
  {
  id: "fall-of-constantinople",
  era: "Modern History",
  year: 1453,
  date: "1453 CE",
  title: "Fall of Constantinople",
  location: "Constantinople",
  description: "The Ottoman Empire, led by Sultan Mehmed II, captures the Byzantine capital, marking the end of the Roman Empire.",
  link: "https://en.wikipedia.org/wiki/Fall_of_Constantinople",
  icon: "fa-solid fa-person-military-to-person",
  image: "https://gertitashkomd.com/wp-content/uploads/2025/05/Tashko-Fall-of-Constantinople-1453.jpg"
  },
  {
  id: "columbus",
  era: "Modern History",
  year: 1492,
  date: "1492",
  title: "Columbus Reaches the Americas",
  location: "The Americas",
  description: "Christopher Columbus's voyage marks the beginning of lasting European contact with the Americas, initiating the Columbian Exchange.",
  link: "https://en.wikipedia.org/wiki/Voyages_of_Christopher_Columbus",
  icon: "fa-solid fa-ship",
  image: "https://cdn.britannica.com/22/143622-050-FD012047/Landing-Columbus-oil-canvas-John-Vanderlyn-US-1846.jpg"
  },
  {
  id: "reformation",
  era: "Modern History",
  year: 1517,
  date: "1517",
  title: "The Protestant Reformation",
  location: "Germany",
  description: "Martin Luther posts his Ninety-five Theses, sparking a schism in Western Christianity and leading to profound religious and political change.",
  link: "https://en.wikipedia.org/wiki/Reformation",
  icon: "fa-solid fa-church",
  image: "https://firstamendment.mtsu.edu/wp-content/uploads/sites/2/2023/06/Luther95theses_0.jpg"
  },
  {
  id: "magellan-circumnavigation",
  era: "Modern History",
  year: 1519,
  date: "1519-1522",
  title: "Magellan's Circumnavigation of the Earth",
  location: "Global",
  description: "The first voyage around the world in human history, it was a Spanish expedition that sailed from Seville in 1519 under the command of Ferdinand Magellan.",
  link: "https://en.wikipedia.org/wiki/Magellan_expedition",
  icon: "fa-solid fa-globe-americas",
  image: "https://capehorners.org/wp-content/uploads/2023/07/truecircumnavigation1.png"
  },
  {
  id: "scientific-revolution",
  era: "Modern History",
  year: 1543,
  date: "c. 1543-1687",
  title: "The Scientific Revolution",
  location: "Europe",
  description: "A series of events that marked the emergence of modern science during the early modern period, when developments in mathematics, physics, astronomy, biology, and chemistry transformed the views of society about nature.",
  link: "https://en.wikipedia.org/wiki/Scientific_Revolution",
  icon: "fa-solid fa-atom",
  image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Jan_Matejko-Astronomer_Copernicus-Conversation_with_God.jpg"
  },
  {
  id: "thirty-years-war",
  era: "Modern History",
  year: 1618,
  date: "1618-1648",
  title: "The Thirty Years' War",
  location: "Central Europe",
  description: "One of the longest and most destructive conflicts in European history, it was a war fought primarily in Central Europe between 1618 and 1648, and was one of the last major religious wars in Europe.",
  link: "https://en.wikipedia.org/wiki/Thirty_Years%27_War",
  icon: "fa-solid fa-swords-laser",
  image: "https://blogs.icrc.org/app/uploads/sites/102/2017/05/800px-Sebastiaan_Vrancx_1573-1647_-_De_plundering_van_Wommelgem_1625-1630_-_D%C3%BCsseldorf_Museum_Kunstpalast_15-08-2012_15-08-12.jpg"
  },
  {
  id: "glorious-revolution",
  era: "Modern History",
  year: 1688,
  date: "1688",
  title: "The Glorious Revolution",
  location: "England",
  description: "The overthrow of King James II of England by a union of English Parliamentarians with the Dutch stadtholder William III, Prince of Orange.",
  link: "https://en.wikipedia.org/wiki/Glorious_Revolution",
  icon: "fa-solid fa-balance-scale-left",
  image: "https://cdn.britannica.com/78/128478-050-990F1F30/William-III-Declaration-of-Right.jpg"
  },
  {
  id: "enlightenment",
  era: "Modern History",
  year: 1688,
  date: "c. 1688-1789",
  title: "The Enlightenment",
  location: "Europe",
  description: "An intellectual and philosophical movement that emphasized reason, individualism, and skepticism, challenging traditional authority.",
  link: "https://en.wikipedia.org/wiki/Age_of_Enlightenment",
  icon: "fa-solid fa-lightbulb",
  image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Jean-Jacques_Rousseau_%28painted_portrait%29.jpg/800px-Jean-Jacques_Rousseau_%28painted_portrait%29.jpg"
  },
  {
  id: "seven-years-war",
  era: "Modern History",
  year: 1756,
  date: "1756-1763",
  title: "The Seven Years' War",
  location: "Global",
  description: "A global conflict fought between 1756 and 1763. It involved every European great power of the time and spanned five continents, affecting Europe, the Americas, West Africa, India, and the Philippines.",
  link: "https://en.wikipedia.org/wiki/Seven_Years%27_War",
  icon: "fa-solid fa-globe",
  image: "https://www.nam.ac.uk/sites/default/files/styles/slice_lg/public/2017-10/132328_slice_0.jpg.webp?itok=HJ4-Kd8b"
  },
  {
  id: "industrial-revolution",
  era: "Modern History",
  year: 1760,
  date: "c. 1760 - 1840",
  title: "The Industrial Revolution",
  location: "Great Britain",
  description: "A period of major industrialization that saw the transition to new manufacturing processes, fundamentally changing society.",
  link: "https://en.wikipedia.org/wiki/Industrial_Revolution",
  icon: "fa-solid fa-industry",
  image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_1.7777777777777777,w_3840,h_2163,g_center/dpr_auto/f_auto/q_auto:eco:sensitive/v1/second_industrial_revolution_gettyimages-51632462-1?_a=BAVAZGDX0"
  },
  {
  id: "american-revolution",
  era: "Modern History",
  year: 1776,
  date: "1776 CE",
  title: "American Declaration of Independence",
  location: "Philadelphia, USA",
  description: "The thirteen American colonies declare independence from Great Britain, leading to the formation of the United States.",
  link: "https://en.wikipedia.org/wiki/United_States_Declaration_of_Independence",
  icon: "fa-solid fa-flag-usa",
  image: "https://cdn.britannica.com/21/143621-159-3EDE9040/Declaration-of-Independence-canvas-rotunda-John-Trumbull-July-4-1776.jpg"
  },
  {
  id: "french-revolution",
  era: "Modern History",
  year: 1789,
  date: "1789 CE",
  title: "The French Revolution",
  location: "Paris, France",
  description: "A period of radical political and societal change in France that ended the monarchy and had a lasting impact on modern history.",
  link: "https://en.wikipedia.org/wiki/French_Revolution",
  icon: "fa-solid fa-torii-gate",
  image: "https://static.wixstatic.com/media/5419df_9d99fd75706848bf88903630a53a7a54~mv2.jpg/v1/fill/w_640,h_424,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/5419df_9d99fd75706848bf88903630a53a7a54~mv2.jpghttps://orion-uploads.openroadmedia.com/md_6780fb194163-napoleon.jpg"
  },
  // Contemporary History
  {
  id: "napoleonic-wars",
  era: "Contemporary History",
  year: 1803,
  date: "1803-1815",
  title: "Napoleonic Wars",
  location: "Europe",
  description: "A series of major global conflicts pitting the French Empire and its allies, led by Napoleon I, against a fluctuating array of European powers.",
  link: "https://en.wikipedia.org/wiki/Napoleonic_Wars",
  icon: "fa-solid fa-chess-king",
  image: "https://orion-uploads.openroadmedia.com/md_6780fb194163-napoleon.jpg"
  },
  {
  id: "communist-manifesto",
  era: "Contemporary History",
  year: 1848,
  date: "1848 CE",
  title: "The Communist Manifesto",
  location: "London, UK",
  description: "Karl Marx and Friedrich Engels publish their political pamphlet, which would become one of the world's most influential political documents.",
  link: "https://en.wikipedia.org/wiki/The_Communist_Manifesto",
  icon: "fa-solid fa-book-skull",
  image: "https://m.media-amazon.com/images/I/71O1MLu9evL._UF894,1000_QL80_.jpg"
  },
  {
  id: "meiji-restoration",
  era: "Contemporary History",
  year: 1868,
  date: "1868",
  title: "Meiji Restoration",
  location: "Japan",
  description: "A political and social revolution in Japan in 1868–89, which ended the power of the shogun and restored the emperor to a central position in Japanese politics and society.",
  link: "https://en.wikipedia.org/wiki/Meiji_Restoration",
  icon: "fa-solid fa-sun",
  image: "https://www.nippon.com/en/ncommon/contents/views/81138/81138.jpg"
  },
  {
  id: "scramble-for-africa",
  era: "Contemporary History",
  year: 1884,
  date: "c. 1884-1914",
  title: "The Scramble for Africa",
  location: "Africa",
  description: "The invasion, occupation, division, and colonization of most of Africa by seven Western European powers during a short period known to historians as the New Imperialism.",
  link: "https://en.wikipedia.org/wiki/Scramble_for_Africa",
  icon: "fa-solid fa-compass",
  image: "https://communist.red/wp-content/uploads/2024/11/Rhodes-Colossus-Scramble-for-Africa.jpg"
  },
  {
  id: "spanish-american-war",
  era: "Contemporary History",
  year: 1898,
  date: "1898",
  title: "Spanish-American War",
  location: "Cuba, Puerto Rico, Philippines",
  description: "A conflict fought between Spain and the United States in 1898. The war ended Spanish colonial rule in the Americas and resulted in U.S. acquisition of territories in the western Pacific and Latin America.",
  link: "https://en.wikipedia.org/wiki/Spanish%E2%80%93American_War",
  icon: "fa-solid fa-bomb",
  image: "https://cdn.britannica.com/36/181736-050-4FA9C071/Theodore-Roosevelt-Rough-Riders-Spanish-American-War-Kurz-1898.jpg"
  },
  {
  id: "panama-canal",
  era: "Contemporary History",
  year: 1904,
  date: "1904-1914",
  title: "Construction of the Panama Canal",
  location: "Panama",
  description: "A major engineering project to build a waterway in Panama that connects the Atlantic Ocean with the Pacific Ocean, built by the United States.",
  link: "https://en.wikipedia.org/wiki/Panama_Canal",
  icon: "fa-solid fa-ship",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_LdLXgZpwRQUN3Lk8rrerD1ZXjvgQ682D5g&s"
  },
  {
  id: "ww1",
  era: "Contemporary History",
  year: 1914,
  date: "1914-1918",
  title: "World War I",
  location: "Global",
  description: "Known as the Great War, it was a global conflict that reshaped the political map of Europe and led to unprecedented casualties.",
  link: "https://en.wikipedia.org/wiki/World_War_I",
  icon: "fa-solid fa-helmet-safety",
  image: "https://www.historyhit.com/app/uploads/2020/07/The_Battle_of_the_Somme_film_image1-3.jpg"
  },
  {
  id: "russian-revolution",
  era: "Contemporary History",
  year: 1917,
  date: "1917 CE",
  title: "Russian Revolution",
  location: "Russia",
  description: "A pair of revolutions that dismantled the Tsarist autocracy and led to the rise of the Soviet Union, the world's first communist state.",
  link: "https://en.wikipedia.org/wiki/Russian_Revolution",
  icon: "fa-solid fa-star",
  image: "https://update.lib.berkeley.edu/wp-content/uploads/2017/09/RUSSIANREV_02.jpg"
  },
  {
  id: "irish-war-of-independence",
  era: "Contemporary History",
  year: 1919,
  date: "1919-1921",
  title: "Irish War of Independence",
  location: "Ireland",
  description: "A guerrilla war fought in Ireland from 1919 to 1921 between the Irish Republican Army and British forces.",
  link: "https://en.wikipedia.org/wiki/Irish_War_of_Independence",
  icon: "fa-solid fa-flag",
  image: "https://www.nam.ac.uk/sites/default/files/2021-11/121136_slice.jpg"
  },
  {
  id: "ww2",
  era: "Contemporary History",
  year: 1939,
  date: "1939-1945",
  title: "World War II",
  location: "Global",
  description: "The deadliest conflict in human history, involving more than 30 countries and resulting in 70 to 85 million fatalities.",
  link: "https://en.wikipedia.org/wiki/World_War_II",
  icon: "fa-solid fa-plane-bomb",
  image: "https://www.historic-newspapers.com/cdn/shop/articles/WW2-timeline-featured-iage_662e418e-ab05-436e-a8ee-94736a47c32c.jpg?v=1749305962&width=1440"
  },
  {
  id: "korean-war",
  era: "Contemporary History",
  year: 1950,
  date: "1950-1953",
  title: "Korean War",
  location: "Korea",
  description: "A war between North Korea (with the support of China and the Soviet Union) and South Korea (with the support of the United Nations, principally the United States).",
  link: "https://en.wikipedia.org/wiki/Korean_War",
  icon: "fa-solid fa-fighter-jet",
  image: "https://www.pbs.org/wgbh/americanexperience/media/filer_public_thumbnails/filer_public/cb/4c/cb4cfe5b-ece9-4c65-a8fa-f3f08f0ef623/superbomb-korean-war-loc.jpg__1000x724_q85_crop_subsampling-2.jpg"
  },
  {
  id: "vietnam-war",
  era: "Contemporary History",
  year: 1955,
  date: "1955-1975",
  title: "Vietnam War",
  location: "Vietnam",
  description: "A long, costly and divisive conflict that pitted the communist government of North Vietnam against South Vietnam and its principal ally, the United States.",
  link: "https://en.wikipedia.org/wiki/Vietnam_War",
  icon: "fa-solid fa-helicopter",
  image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_1.7777777777777777,w_1920,h_1080,g_auto/dpr_auto/f_auto/q_auto:eco/v1/vietnam-war-gettyimages-615208290?_a=BAVAZGDX0"
  },
  {
  id: "cuban-missile-crisis",
  era: "Contemporary History",
  year: 1962,
  date: "1962",
  title: "Cuban Missile Crisis",
  location: "Cuba, USA, Soviet Union",
  description: "A 13-day confrontation between the United States and the Soviet Union initiated by the American discovery of Soviet ballistic missile deployment in Cuba.",
  link: "https://en.wikipedia.org/wiki/Cuban_Missile_Crisis",
  icon: "fa-solid fa-radiation",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZSBaru-F0fb35WgHxxvDoqChX8pz-ApX23Q&s"
  },
  {
  id: "moon-landing",
  era: "Contemporary History",
  year: 1969,
  date: "1969",
  title: "Apollo 11 Moon Landing",
  location: "The Moon",
  description: "Neil Armstrong and Buzz Aldrin become the first humans to walk on the Moon, a monumental achievement for science and exploration.",
  link: "https://en.wikipedia.org/wiki/Apollo_11",
  icon: "fa-solid fa-rocket",
  image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Aldrin_Apollo_11_original.jpg/800px-Aldrin_Apollo_11_original.jpg"
  },
  {
  id: "fall-of-berlin-wall",
  era: "Contemporary History",
  year: 1989,
  date: "1989 CE",
  title: "Fall of the Berlin Wall",
  location: "Berlin, Germany",
  description: "The pivotal event that symbolized the end of the Cold War and led to the reunification of Germany.",
  link: "https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall",
  icon: "fa-solid fa-bridge-circle-xmark",
  image: "https://media.cnn.com/api/v1/images/stellar/prod/191107162239-berlin-wall-fall-1.jpg?q=w_3748,h_2457,x_0,y_0,c_fill"
  },
  {
  id: "world-wide-web",
  era: "Contemporary History",
  year: 1991,
  date: "1991",
  title: "The World Wide Web becomes Public",
  location: "Global",
  description: "CERN makes the World Wide Web project public, sparking the digital revolution and fundamentally changing how we access information.",
  link: "https://en.wikipedia.org/wiki/History_of_the_World_Wide_Web",
  icon: "fa-solid fa-globe",
  image: "https://www.firstonline.info/wp-content/uploads/2024/08/www.webp"
  },
  {
  id: "end-of-apartheid",
  era: "Contemporary History",
  year: 1994,
  date: "1994",
  title: "End of Apartheid in South Africa",
  location: "South Africa",
  description: "The end of the system of institutionalised racial segregation that had existed in South Africa and South West Africa from 1948.",
  link: "https://en.wikipedia.org/wiki/Apartheid",
  icon: "fa-solid fa-gavel",
  image: "https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/kch2zfpxesujzcyuuzc7.jpg"
  },
  {
  id: "rwandan-genocide",
  era: "Contemporary History",
  year: 1994,
  date: "1994",
  title: "Rwandan Genocide",
  location: "Rwanda",
  description: "A mass slaughter of Tutsi in Rwanda during a 100-day period from 7 April to mid-July 1994 by members of the Hutu majority government.",
  link: "https://en.wikipedia.org/wiki/Rwandan_genocide",
  icon: "fa-solid fa-sad-tear",
  image: "https://www.ramapo.edu/holocaust/wp-content/uploads/sites/31/2024/04/HIST329FA23RE-13.jpg"
  },
  {
  id: "9-11-attacks",
  era: "Contemporary History",
  year: 2001,
  date: "2001",
  title: "September 11 Attacks",
  location: "United States",
  description: "A series of four coordinated terrorist attacks by the Islamic terrorist group al-Qaeda against the United States on the morning of September 11, 2001.",
  link: "https://en.wikipedia.org/wiki/September_11_attacks",
  icon: "fa-solid fa-building-wheat",
  image: "https://upload.wikimedia.org/wikipedia/commons/3/35/WTC_smoking_on_9-11.jpeg"
  },
  {
  id: "2008-financial-crisis",
  era: "Contemporary History",
  year: 2008,
  date: "2008",
  title: "2008 Financial Crisis",
  location: "Global",
  description: "A severe worldwide economic crisis that occurred in the late 2000s. It was the most serious financial crisis since the Great Depression.",
  link: "https://en.wikipedia.org/wiki/Great_Recession",
  icon: "fa-solid fa-chart-line-down",
  image: "https://miro.medium.com/0*_us4B6mENQYd7Zbj.jpg"
  },
  {
  id: "arab-spring",
  era: "Contemporary History",
  year: 2010,
  date: "2010-2012",
  title: "Arab Spring",
  location: "Middle East and North Africa",
  description: "A series of anti-government protests, uprisings, and armed rebellions that spread across much of the Arab world in the early 2010s.",
  link: "https://en.wikipedia.org/wiki/Arab_Spring",
  icon: "fa-solid fa-dove",
  image: "https://www.aljazeera.com/wp-content/uploads/2011/05/20115131629841734_20.jpeg?resize=1200%2C675"
  },
  {
  id: "covid-19",
  era: "Contemporary History",
  year: 2020,
  date: "2020 CE",
  title: "COVID-19 Pandemic",
  location: "Global",
  description: "A worldwide pandemic caused by a novel coronavirus that led to global social and economic disruption, lockdowns, and millions of deaths.",
  link: "https://en.wikipedia.org/wiki/COVID-19_pandemic",
  icon: "fa-solid fa-virus-covid",
  image: "https://www.un.org/sites/un2.un.org/files/field/image/1583952355.1997.jpg"
  }
  ];