// src/data.js

export const historicalEvents = [
    // Ancient History
    {
      id: "agriculture",
      era: "Ancient History",
      year: -10000,
      date: "c. 10,000 BCE",
      title: "The Agricultural Revolution",
      location: "Fertile Crescent",
      description: "Humans begin to transition from hunter-gatherer societies to settled agricultural communities, domesticating plants and animals.",
      link: "https://en.wikipedia.org/wiki/Neolithic_Revolution",
      icon: "fa-solid fa-wheat-awn",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Figurine_of_a_woman_and_child_from_the_Plo%C4%8Dnik_site_%28Vin%C4%8Da_culture%29.jpg/800px-Figurine_of_a_woman_and_child_from_the_Plo%C4%8Dnik_site_%28Vin%C4%8Da_culture%29.jpg"
    },
    {
      id: "sumer",
      era: "Ancient History",
      year: -3500,
      date: "c. 3500 BCE",
      title: "The Rise of Sumer",
      location: "Mesopotamia",
      description: "The world's first civilization emerges, inventing writing (cuneiform), the wheel, and creating the first city-states like Uruk.",
      link: "https://en.wikipedia.org/wiki/Sumer",
      icon: "fa-solid fa-city",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Stele_of_the_Vultures_detail_01.jpg/800px-Stele_of_the_Vultures_detail_01.jpg"
    },
    {
      id: "pyramids",
      era: "Ancient History",
      year: -2560,
      date: "c. 2560 BCE",
      title: "Great Pyramid of Giza",
      location: "Giza, Egypt",
      description: "Completed as a tomb for Pharaoh Khufu, it's a masterpiece of ancient engineering and the only surviving wonder of the ancient world.",
      link: "https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza",
      icon: "fa-solid fa-landmark",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Giza_pyramid_complex_%28main_centered_version%29.jpg/1280px-Giza_pyramid_complex_%28main_centered_version%29.jpg"
    },
    {
      id: "hammurabi",
      era: "Ancient History",
      year: -1780,
      date: "c. 1780 BCE",
      title: "Code of Hammurabi",
      location: "Babylon",
      description: "One of the earliest and most complete written legal codes, proclaimed by the Babylonian king Hammurabi.",
      link: "https://en.wikipedia.org/wiki/Code_of_Hammurabi",
      icon: "fa-solid fa-scale-balanced",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Code_of_Hammurabi_in_the_Louvre_Museum.jpg/800px-Code_of_Hammurabi_in_the_Louvre_Museum.jpg"
    },
     {
      id: "bronze-age-collapse",
      era: "Ancient History",
      year: -1200,
      date: "c. 1200 BCE",
      title: "Late Bronze Age Collapse",
      location: "Eastern Mediterranean",
      description: "A widespread societal collapse involving the decline of major civilizations like the Mycenaeans, Hittites, and parts of the Egyptian New Kingdom.",
      link: "https://en.wikipedia.org/wiki/Late_Bronze_Age_collapse",
      icon: "fa-solid fa-house-fire",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Sea_Peoples.svg/1024px-Sea_Peoples.svg.png"
    },
    {
      id: "olympics",
      era: "Ancient History",
      year: -776,
      date: "c. 776 BCE",
      title: "First Olympic Games",
      location: "Olympia, Greece",
      description: "The ancient Olympic Games are founded, a festival of sport and culture that brought the Greek world together.",
      link: "https://en.wikipedia.org/wiki/Ancient_Olympic_Games",
      icon: "fa-solid fa-trophy",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Discus_thrower_Lancellotti_Massimo_Inv126371_n2.jpg/800px-Discus_thrower_Lancellotti_Massimo_Inv126371_n2.jpg"
    },
    
    // Classical Antiquity
    {
      id: "buddha",
      era: "Classical Antiquity",
      year: -500,
      date: "c. 5th Century BCE",
      title: "Life of the Buddha",
      location: "Ancient India",
      description: "Siddhartha Gautama achieves enlightenment, becoming the Buddha and founding Buddhism, a major world religion.",
      link: "https://en.wikipedia.org/wiki/The_Buddha",
      icon: "fa-solid fa-om",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg/800px-Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg"
    },
    {
      id: "alexander",
      era: "Classical Antiquity",
      year: -334,
      date: "334-323 BCE",
      title: "Conquests of Alexander the Great",
      location: "Greece to India",
      description: "Alexander's military campaigns create one of the largest empires of the ancient world, spreading Greek culture across a vast area.",
      link: "https://en.wikipedia.org/wiki/Alexander_the_Great",
      icon: "fa-solid fa-horse",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Alexander_the_Great_mosaic.jpg/1024px-Alexander_the_Great_mosaic.jpg"
    },
      {
      id: "qin-dynasty",
      era: "Classical Antiquity",
      year: -221,
      date: "221 BCE",
      title: "Qin Shi Huang Unifies China",
      location: "China",
      description: "The end of the Warring States period marks the beginning of Imperial China. The Great Wall and Terracotta Army are constructed.",
      link: "https://en.wikipedia.org/wiki/Qin_Shi_Huang",
      icon: "fa-solid fa-dragon",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Terracotta_warriors_in_Xian.jpg/1024px-Terracotta_warriors_in_Xian.jpg"
    },
    {
      id: "augustus",
      era: "Classical Antiquity",
      year: -27,
      date: "27 BCE - 14 CE",
      title: "Reign of Augustus",
      location: "Roman Empire",
      description: "The reign of the first Roman Emperor, Augustus, marks the end of the Roman Republic and the beginning of the Pax Romana.",
      link: "https://en.wikipedia.org/wiki/Augustus",
      icon: "fa-solid fa-crown",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Augusto_di_Prima_Porta%2C_inv._2290%2C_02.jpg/800px-Augusto_di_Prima_Porta%2C_inv._2290%2C_02.jpg"
    },
    {
      id: "jesus",
      era: "Classical Antiquity",
      year: 30,
      date: "c. 30-33 CE",
      title: "Crucifixion of Jesus",
      location: "Jerusalem, Judea",
      description: "The execution of Jesus of Nazareth, a central event in Christianity, which forms the basis of the world's largest religion.",
      link: "https://en.wikipedia.org/wiki/Crucifixion_of_Jesus",
      icon: "fa-solid fa-cross",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Valmy_Chapel_Christ_in_agony.jpg/800px-Valmy_Chapel_Christ_in_agony.jpg"
    },
  
    // Post-Classical History
    {
      id: "fall-of-rome",
      era: "Post-Classical History",
      year: 476,
      date: "476 CE",
      title: "Fall of the Western Roman Empire",
      location: "Rome, Italy",
      description: "The deposition of the last emperor, Romulus Augustulus, by Odoacer is traditionally seen as the end of the Western Roman Empire.",
      link: "https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire",
      icon: "fa-solid fa-person-military-falling",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Jean-Joseph-Benjamin-Constant_The_Last_of_the_Roman_Emperors.jpg/1024px-Jean-Joseph-Benjamin-Constant_The_Last_of_the_Roman_Emperors.jpg"
    },
    {
      id: "islam",
      era: "Post-Classical History",
      year: 610,
      date: "c. 610 CE",
      title: "The Revelations of Islam",
      location: "Mecca, Arabia",
      description: "The Prophet Muhammad begins receiving divine revelations, forming the basis of the Quran and the Islamic faith.",
      link: "https://en.wikipedia.org/wiki/Muhammad",
      icon: "fa-solid fa-moon",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Siyer-i_Nebi_-_Mohammed_and_the_four_archangels.jpg/800px-Siyer-i_Nebi_-_Mohammed_and_the_four_archangels.jpg"
    },
    {
      id: "charlemagne",
      era: "Post-Classical History",
      year: 800,
      date: "800 CE",
      title: "Coronation of Charlemagne",
      location: "Rome, Italy",
      description: "Pope Leo III crowns Charlemagne as the first Holy Roman Emperor, uniting much of Western Europe for the first time since the Romans.",
      link: "https://en.wikipedia.org/wiki/Charlemagne",
      icon: "fa-solid fa-hat-wizard",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Albrecht_D%C3%BCrer_-_Emperor_Charlemagne_%28Nuremberg%29.jpg/800px-Albrecht_D%C3%BCrer_-_Emperor_Charlemagne_%28Nuremberg%29.jpg"
    },
    {
      id: "great-schism",
      era: "Post-Classical History",
      year: 1054,
      date: "1054 CE",
      title: "The Great Schism",
      location: "Rome & Constantinople",
      description: "The formal split between the Western Roman Catholic and Eastern Orthodox churches, a division that persists to this day.",
      link: "https://en.wikipedia.org/wiki/East%E2%80%93West_Schism",
      icon: "fa-solid fa-people-arrows",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Hagia_Sophia_Mars_2013.jpg/1024px-Hagia_Sophia_Mars_2013.jpg"
    },
    {
      id: "genghis-khan",
      era: "Post-Classical History",
      year: 1206,
      date: "1206",
      title: "Genghis Khan Unites the Mongols",
      location: "Central Asia",
      description: "Genghis Khan establishes the Mongol Empire, which would become the largest contiguous land empire in history.",
      link: "https://en.wikipedia.org/wiki/Genghis_Khan",
      icon: "fa-solid fa-horse-head",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Genghis_Khan_painting_in_National_Palace_Museum.jpg/800px-Genghis_Khan_painting_in_National_Palace_Museum.jpg"
    },
    {
      id: "magna-carta",
      era: "Post-Classical History",
      year: 1215,
      date: "1215 CE",
      title: "Magna Carta Sealed",
      location: "Runnymede, England",
      description: "King John of England is forced to sign the 'Great Charter', a foundational document for constitutional law and individual liberties.",
      link: "https://en.wikipedia.org/wiki/Magna_Carta",
      icon: "fa-solid fa-scroll",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg/800px-Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg"
    },
    {
      id: "black-death",
      era: "Post-Classical History",
      year: 1347,
      date: "1347-1351 CE",
      title: "The Black Death",
      location: "Eurasia & North Africa",
      description: "One of the most devastating pandemics in human history, it resulted in the deaths of an estimated 75–200 million people.",
      link: "https://en.wikipedia.org/wiki/Black_Death",
      icon: "fa-solid fa-skull-crossbones",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Triumph_of_Death_by_Pieter_Bruegel_the_Elder.jpg/1280px-Triumph_of_Death_by_Pieter_Bruegel_the_Elder.jpg"
    },
  
    // Modern History
    {
      id: "renaissance",
      era: "Modern History",
      year: 1400,
      date: "c. 1400-1600",
      title: "The Renaissance",
      location: "Europe",
      description: "A fervent period of European cultural, artistic, political and economic 'rebirth' following the Middle Ages.",
      link: "https://en.wikipedia.org/wiki/Renaissance",
      icon: "fa-solid fa-palette",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Leonardo_da_Vinci_%281452-1519%29_-_The_Last_Supper_%281495-1498%29.jpg/1280px-Leonardo_da_Vinci_%281452-1519%29_-_The_Last_Supper_%281495-1498%29.jpg"
    },
    {
      id: "fall-of-constantinople",
      era: "Modern History",
      year: 1453,
      date: "1453 CE",
      title: "Fall of Constantinople",
      location: "Constantinople",
      description: "The Ottoman Empire, led by Sultan Mehmed II, captures the Byzantine capital, marking the end of the Roman Empire.",
      link: "https://en.wikipedia.org/wiki/Fall_of_Constantinople",
      icon: "fa-solid fa-person-military-to-person",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Zonaro_Capture_of_Constantinople.jpg/1024px-Zonaro_Capture_of_Constantinople.jpg"
    },
    {
      id: "columbus",
      era: "Modern History",
      year: 1492,
      date: "1492",
      title: "Columbus Reaches the Americas",
      location: "The Americas",
      description: "Christopher Columbus's voyage marks the beginning of lasting European contact with the Americas, initiating the Columbian Exchange.",
      link: "https://en.wikipedia.org/wiki/Voyages_of_Christopher_Columbus",
      icon: "fa-solid fa-ship",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Col%C3%B3n_tomando_posesi%C3%B3n.jpg/1024px-Col%C3%B3n_tomando_posesi%C3%B3n.jpg"
    },
    {
      id: "reformation",
      era: "Modern History",
      year: 1517,
      date: "1517",
      title: "The Protestant Reformation",
      location: "Germany",
      description: "Martin Luther posts his Ninety-five Theses, sparking a schism in Western Christianity and leading to profound religious and political change.",
      link: "https://en.wikipedia.org/wiki/Reformation",
      icon: "fa-solid fa-church",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Lucas_Cranach_d.%C3%84._-_Martin_Luther%2C_1528_%28Veste_Coburg%29.jpg/800px-Lucas_Cranach_d.%C3%84._-_Martin_Luther%2C_1528_%28Veste_Coburg%29.jpg"
    },
    {
      id: "enlightenment",
      era: "Modern History",
      year: 1688,
      date: "c. 1688-1789",
      title: "The Enlightenment",
      location: "Europe",
      description: "An intellectual and philosophical movement that emphasized reason, individualism, and skepticism, challenging traditional authority.",
      link: "https://en.wikipedia.org/wiki/Age_of_Enlightenment",
      icon: "fa-solid fa-lightbulb",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Jean-Jacques_Rousseau_%28painted_portrait%29.jpg/800px-Jean-Jacques_Rousseau_%28painted_portrait%29.jpg"
    },
    {
      id: "industrial-revolution",
      era: "Modern History",
      year: 1760,
      date: "c. 1760 - 1840",
      title: "The Industrial Revolution",
      location: "Great Britain",
      description: "A period of major industrialization that saw the transition to new manufacturing processes, fundamentally changing society.",
      link: "https://en.wikipedia.org/wiki/Industrial_Revolution",
      icon: "fa-solid fa-industry",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Arkwright_Richard_painted_by_Joseph_Wright_of_Derby.jpg/800px-Arkwright_Richard_painted_by_Joseph_Wright_of_Derby.jpg"
    },
    {
      id: "american-revolution",
      era: "Modern History",
      year: 1776,
      date: "1776 CE",
      title: "American Declaration of Independence",
      location: "Philadelphia, USA",
      description: "The thirteen American colonies declare independence from Great Britain, leading to the formation of the United States.",
      link: "https://en.wikipedia.org/wiki/United_States_Declaration_of_Independence",
      icon: "fa-solid fa-flag-usa",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/John_Trumbull_-_The_Declaration_of_Independence.jpg/1280px-John_Trumbull_-_The_Declaration_of_Independence.jpg"
    },
    {
      id: "french-revolution",
      era: "Modern History",
      year: 1789,
      date: "1789 CE",
      title: "The French Revolution",
      location: "Paris, France",
      description: "A period of radical political and societal change in France that ended the monarchy and had a lasting impact on modern history.",
      link: "https://en.wikipedia.org/wiki/French_Revolution",
      icon: "fa-solid fa-torii-gate",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Prise_de_la_Bastille.jpg/1024px-Prise_de_la_Bastille.jpg"
    },
  
    // Contemporary History
    {
      id: "napoleonic-wars",
      era: "Contemporary History",
      year: 1803,
      date: "1803-1815",
      title: "Napoleonic Wars",
      location: "Europe",
      description: "A series of major global conflicts pitting the French Empire and its allies, led by Napoleon I, against a fluctuating array of European powers.",
      link: "https://en.wikipedia.org/wiki/Napoleonic_Wars",
      icon: "fa-solid fa-chess-king",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Jacques-Louis_David_-_The_Coronation_of_Napoleon_%281805-1807%29.jpg/1280px-Jacques-Louis_David_-_The_Coronation_of_Napoleon_%281805-1807%29.jpg"
    },
    {
      id: "communist-manifesto",
      era: "Contemporary History",
      year: 1848,
      date: "1848 CE",
      title: "The Communist Manifesto",
      location: "London, UK",
      description: "Karl Marx and Friedrich Engels publish their political pamphlet, which would become one of the world's most influential political documents.",
      link: "https://en.wikipedia.org/wiki/The_Communist_Manifesto",
      icon: "fa-solid fa-book-skull",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Marx_and_Engels_The_Communist_Manifesto_title_page_1848.jpg/800px-Marx_and_Engels_The_Communist_Manifesto_title_page_1848.jpg"
    },
    {
      id: "ww1",
      era: "Contemporary History",
      year: 1914,
      date: "1914-1918",
      title: "World War I",
      location: "Global",
      description: "Known as the Great War, it was a global conflict that reshaped the political map of Europe and led to unprecedented casualties.",
      link: "https://en.wikipedia.org/wiki/World_War_I",
      icon: "fa-solid fa-helmet-safety",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Battle_of_the_Somme_1916.jpg/1024px-Battle_of_the_Somme_1916.jpg"
    },
    {
      id: "russian-revolution",
      era: "Contemporary History",
      year: 1917,
      date: "1917 CE",
      title: "Russian Revolution",
      location: "Russia",
      description: "A pair of revolutions that dismantled the Tsarist autocracy and led to the rise of the Soviet Union, the world's first communist state.",
      link: "https://en.wikipedia.org/wiki/Russian_Revolution",
      icon: "fa-solid fa-star",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Lenin_Speaks_in_Moscow_on_5_May_1920_-_GPN-2002-000137.jpg/1024px-Lenin_Speaks_in_Moscow_on_5_May_1920_-_GPN-2002-000137.jpg"
    },
    {
      id: "ww2",
      era: "Contemporary History",
      year: 1939,
      date: "1939-1945",
      title: "World War II",
      location: "Global",
      description: "The deadliest conflict in human history, involving more than 30 countries and resulting in 70 to 85 million fatalities.",
      link: "https://en.wikipedia.org/wiki/World_War_II",
      icon: "fa-solid fa-plane-bomb",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Bundesarchiv_Bild_101I-299-1805-16%2C_Russland%2C_Soldaten_der_Waffen-SS_im_Sch%C3%BCtzengraben.jpg/1024px-Bundesarchiv_Bild_101I-299-1805-16%2C_Russland%2C_Soldaten_der_Waffen-SS_im_Sch%C3%BCtzengraben.jpg"
    },
    {
      id: "moon-landing",
      era: "Contemporary History",
      year: 1969,
      date: "1969",
      title: "Apollo 11 Moon Landing",
      location: "The Moon",
      description: "Neil Armstrong and Buzz Aldrin become the first humans to walk on the Moon, a monumental achievement for science and exploration.",
      link: "https://en.wikipedia.org/wiki/Apollo_11",
      icon: "fa-solid fa-rocket",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Aldrin_Apollo_11_original.jpg/800px-Aldrin_Apollo_11_original.jpg"
    },
    {
      id: "fall-of-berlin-wall",
      era: "Contemporary History",
      year: 1989,
      date: "1989 CE",
      title: "Fall of the Berlin Wall",
      location: "Berlin, Germany",
      description: "The pivotal event that symbolized the end of the Cold War and led to the reunification of Germany.",
      link: "https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall",
      icon: "fa-solid fa-bridge-circle-xmark",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Berlinermauer.jpg/1024px-Berlinermauer.jpg"
    },
    {
      id: "world-wide-web",
      era: "Contemporary History",
      year: 1991,
      date: "1991",
      title: "The World Wide Web becomes Public",
      location: "Global",
      description: "CERN makes the World Wide Web project public, sparking the digital revolution and fundamentally changing how we access information.",
      link: "https://en.wikipedia.org/wiki/History_of_the_World_Wide_Web",
      icon: "fa-solid fa-globe",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Sir_Tim_Berners-Lee_%28cropped%29.jpg/800px-Sir_Tim_Berners-Lee_%28cropped%29.jpg"
    },
    {
      id: "covid-19",
      era: "Contemporary History",
      year: 2020,
      date: "2020 CE",
      title: "COVID-19 Pandemic",
      location: "Global",
      description: "A worldwide pandemic caused by a novel coronavirus that led to global social and economic disruption, lockdowns, and millions of deaths.",
      link: "https://en.wikipedia.org/wiki/COVID-19_pandemic",
      icon: "fa-solid fa-virus-covid",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Reproduction_of_the_COVID-19_virus.jpg/1024px-Reproduction_of_the_COVID-19_virus.jpg"
    }
  ];
  