// src/data.js

export const historicalEvents = [
    // Ancient History
    {
      id: "agriculture",
      era: "Ancient History",
      year: -10000,
      date: "c. 10,000 BCE",
      title: "The Agricultural Revolution",
      location: "Fertile Crescent",
      description: "Humans begin to transition from hunter-gatherer societies to settled agricultural communities, domesticating plants and animals.",
      link: "https://en.wikipedia.org/wiki/Neolithic_Revolution",
      icon: "fa-solid fa-wheat-awn",
      image: "https://www.ancient-origins.net/sites/default/files/field/image/Neolithic-revolution-ancient-farmers.jpg"
    },
    {
      id: "sumer",
      era: "Ancient History",
      year: -3500,
      date: "c. 3500 BCE",
      title: "The Rise of Sumer",
      location: "Mesopotamia",
      description: "The world's first civilization emerges, inventing writing (cuneiform), the wheel, and creating the first city-states like Uruk.",
      link: "https://en.wikipedia.org/wiki/Sumer",
      icon: "fa-solid fa-city",
      image: "https://www.realmofhistory.com/wp-content/uploads/2023/07/reconstruction-ur-city-sumerian_1-770x437.jpg"
    },
    {
      id: "pyramids",
      era: "Ancient History",
      year: -2560,
      date: "c. 2560 BCE",
      title: "Great Pyramid of Giza",
      location: "Giza, Egypt",
      description: "Completed as a tomb for Pharaoh Khufu, it's a masterpiece of ancient engineering and the only surviving wonder of the ancient world.",
      link: "https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza",
      icon: "fa-solid fa-landmark",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pyramids_of_the_Giza_Necropolis.jpg/960px-Pyramids_of_the_Giza_Necropolis.jpg"
    },
    {
      id: "hammurabi",
      era: "Ancient History",
      year: -1780,
      date: "c. 1780 BCE",
      title: "Code of Hammurabi",
      location: "Babylon",
      description: "One of the earliest and most complete written legal codes, proclaimed by the Babylonian king Hammurabi.",
      link: "https://en.wikipedia.org/wiki/Code_of_Hammurabi",
      icon: "fa-solid fa-scale-balanced",
      image: "https://cdn.britannica.com/89/82589-050-98AA8FA9/Hammurabi-god-Babylon.jpg"
    },
     {
      id: "bronze-age-collapse",
      era: "Ancient History",
      year: -1200,
      date: "c. 1200 BCE",
      title: "Late Bronze Age Collapse",
      location: "Eastern Mediterranean",
      description: "A widespread societal collapse involving the decline of major civilizations like the Mycenaeans, Hittites, and parts of the Egyptian New Kingdom.",
      link: "https://en.wikipedia.org/wiki/Late_Bronze_Age_collapse",
      icon: "fa-solid fa-house-fire",
      image: "https://retrospectjournal.com/wp-content/uploads/2022/12/1024px-keuninck_coninck_kerstiaen_de_-_fire_of_troy.jpg?w=1024"
    },
    {
      id: "olympics",
      era: "Ancient History",
      year: -776,
      date: "c. 776 BCE",
      title: "First Olympic Games",
      location: "Olympia, Greece",
      description: "The ancient Olympic Games are founded, a festival of sport and culture that brought the Greek world together.",
      link: "https://en.wikipedia.org/wiki/Ancient_Olympic_Games",
      icon: "fa-solid fa-trophy",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUlQMIIp0EyeApaIHlMs9I_q1j86ALdfb1Bg&s"
    },
    
    // Classical Antiquity
    {
      id: "buddha",
      era: "Classical Antiquity",
      year: -500,
      date: "c. 5th Century BCE",
      title: "Life of the Buddha",
      location: "Ancient India",
      description: "Siddhartha Gautama achieves enlightenment, becoming the Buddha and founding Buddhism, a major world religion.",
      link: "https://en.wikipedia.org/wiki/The_Buddha",
      icon: "fa-solid fa-om",
      image: "https://www.vridhamma.org/sites/default/files/picture-bar/Life%20of%20the%20Buddha_1.jpg"
    },
    {
      id: "alexander",
      era: "Classical Antiquity",
      year: -334,
      date: "334-323 BCE",
      title: "Conquests of Alexander the Great",
      location: "Greece to India",
      description: "Alexander's military campaigns create one of the largest empires of the ancient world, spreading Greek culture across a vast area.",
      link: "https://en.wikipedia.org/wiki/Alexander_the_Great",
      icon: "fa-solid fa-horse",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Alexander_the_Great_mosaic.jpg/1024px-Alexander_the_Great_mosaic.jpg"
    },
      {
      id: "qin-dynasty",
      era: "Classical Antiquity",
      year: -221,
      date: "221 BCE",
      title: "Qin Shi Huang Unifies China",
      location: "China",
      description: "The end of the Warring States period marks the beginning of Imperial China. The Great Wall and Terracotta Army are constructed.",
      link: "https://en.wikipedia.org/wiki/Qin_Shi_Huang",
      icon: "fa-solid fa-dragon",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/QinShiHuang19century.jpg/1200px-QinShiHuang19century.jpg"
    },
    {
      id: "augustus",
      era: "Classical Antiquity",
      year: -27,
      date: "27 BCE - 14 CE",
      title: "Reign of Augustus",
      location: "Roman Empire",
      description: "The reign of the first Roman Emperor, Augustus, marks the end of the Roman Republic and the beginning of the Pax Romana.",
      link: "https://en.wikipedia.org/wiki/Augustus",
      icon: "fa-solid fa-crown",
      image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_2,w_3840,h_1920,g_auto/dpr_auto/f_auto/q_auto:eco/v1/augustus-caesar-587488458?_a=BAVAZGDX0"
    },
    {
      id: "jesus",
      era: "Classical Antiquity",
      year: 30,
      date: "c. 30-33 CE",
      title: "Crucifixion of Jesus",
      location: "Jerusalem, Judea",
      description: "The execution of Jesus of Nazareth, a central event in Christianity, which forms the basis of the world's largest religion.",
      link: "https://en.wikipedia.org/wiki/Crucifixion_of_Jesus",
      icon: "fa-solid fa-cross",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-QIRmV2ALmJu4r_PQF_6RO42BCfX1r1ttJA&s"
    },
  
    // Post-Classical History
    {
      id: "fall-of-rome",
      era: "Post-Classical History",
      year: 476,
      date: "476 CE",
      title: "Fall of the Western Roman Empire",
      location: "Rome, Italy",
      description: "The deposition of the last emperor, Romulus Augustulus, by Odoacer is traditionally seen as the end of the Western Roman Empire.",
      link: "https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire",
      icon: "fa-solid fa-person-military-falling",
      image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,w_1200,h_630,g_auto/dpr_auto/f_auto/q_auto:eco/v1/gettyimages-802428712"
    },
    {
      id: "islam",
      era: "Post-Classical History",
      year: 610,
      date: "c. 610 CE",
      title: "The Revelations of Islam",
      location: "Mecca, Arabia",
      description: "The Prophet Muhammad begins receiving divine revelations, forming the basis of the Quran and the Islamic faith.",
      link: "https://en.wikipedia.org/wiki/Muhammad",
      icon: "fa-solid fa-moon",
      image: "https://mahadsunnah.com/wp-content/uploads/2022/11/347bc51242fe542208cc710cda9a87d0.webp"
    },
    {
      id: "charlemagne",
      era: "Post-Classical History",
      year: 800,
      date: "800 CE",
      title: "Coronation of Charlemagne",
      location: "Rome, Italy",
      description: "Pope Leo III crowns Charlemagne as the first Holy Roman Emperor, uniting much of Western Europe for the first time since the Romans.",
      link: "https://en.wikipedia.org/wiki/Charlemagne",
      icon: "fa-solid fa-hat-wizard",
      image: "https://cdn.mos.cms.futurecdn.net/v2/t:0,l:525,cw:1350,ch:1350,q:80,w:1350/MRQBaH5S7udd5FQmKkbzTn.jpg"
    },
    {
      id: "great-schism",
      era: "Post-Classical History",
      year: 1054,
      date: "1054 CE",
      title: "The Great Schism",
      location: "Rome & Constantinople",
      description: "The formal split between the Western Roman Catholic and Eastern Orthodox churches, a division that persists to this day.",
      link: "https://en.wikipedia.org/wiki/East%E2%80%93West_Schism",
      icon: "fa-solid fa-people-arrows",
      image: "https://i.ytimg.com/vi/r73ixUECwHs/maxresdefault.jpg"
    },
    {
      id: "genghis-khan",
      era: "Post-Classical History",
      year: 1206,
      date: "1206",
      title: "Genghis Khan Unites the Mongols",
      location: "Central Asia",
      description: "Genghis Khan establishes the Mongol Empire, which would become the largest contiguous land empire in history.",
      link: "https://en.wikipedia.org/wiki/Genghis_Khan",
      icon: "fa-solid fa-horse-head",
      image: "https://media.newyorker.com/photos/65831f8b6186c093c0ab6968/16:9/w_2560,h_1440,c_limit/240101_r43571.jpg"
    },
    {
      id: "magna-carta",
      era: "Post-Classical History",
      year: 1215,
      date: "1215 CE",
      title: "Magna Carta Sealed",
      location: "Runnymede, England",
      description: "King John of England is forced to sign the 'Great Charter', a foundational document for constitutional law and individual liberties.",
      link: "https://en.wikipedia.org/wiki/Magna_Carta",
      icon: "fa-solid fa-scroll",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg/800px-Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg"
    },
    {
      id: "black-death",
      era: "Post-Classical History",
      year: 1347,
      date: "1347-1351 CE",
      title: "The Black Death",
      location: "Eurasia & North Africa",
      description: "One of the most devastating pandemics in human history, it resulted in the deaths of an estimated 75–200 million people.",
      link: "https://en.wikipedia.org/wiki/Black_Death",
      icon: "fa-solid fa-skull-crossbones",
      image: "https://www.historic-uk.com/wp-content/uploads/2017/06/black-death-2800x1440.jpg"
    },
  
    // Modern History
    {
      id: "renaissance",
      era: "Modern History",
      year: 1400,
      date: "c. 1400-1600",
      title: "The Renaissance",
      location: "Europe",
      description: "A fervent period of European cultural, artistic, political and economic 'rebirth' following the Middle Ages.",
      link: "https://en.wikipedia.org/wiki/Renaissance",
      icon: "fa-solid fa-palette",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Leonardo_da_Vinci_%281452-1519%29_-_The_Last_Supper_%281495-1498%29.jpg/1280px-Leonardo_da_Vinci_%281452-1519%29_-_The_Last_Supper_%281495-1498%29.jpg"
    },
    {
      id: "fall-of-constantinople",
      era: "Modern History",
      year: 1453,
      date: "1453 CE",
      title: "Fall of Constantinople",
      location: "Constantinople",
      description: "The Ottoman Empire, led by Sultan Mehmed II, captures the Byzantine capital, marking the end of the Roman Empire.",
      link: "https://en.wikipedia.org/wiki/Fall_of_Constantinople",
      icon: "fa-solid fa-person-military-to-person",
      image: "https://gertitashkomd.com/wp-content/uploads/2025/05/Tashko-Fall-of-Constantinople-1453.jpg"
    },
    {
      id: "columbus",
      era: "Modern History",
      year: 1492,
      date: "1492",
      title: "Columbus Reaches the Americas",
      location: "The Americas",
      description: "Christopher Columbus's voyage marks the beginning of lasting European contact with the Americas, initiating the Columbian Exchange.",
      link: "https://en.wikipedia.org/wiki/Voyages_of_Christopher_Columbus",
      icon: "fa-solid fa-ship",
      image: "https://cdn.britannica.com/22/143622-050-FD012047/Landing-Columbus-oil-canvas-John-Vanderlyn-US-1846.jpg"
    },
    {
      id: "reformation",
      era: "Modern History",
      year: 1517,
      date: "1517",
      title: "The Protestant Reformation",
      location: "Germany",
      description: "Martin Luther posts his Ninety-five Theses, sparking a schism in Western Christianity and leading to profound religious and political change.",
      link: "https://en.wikipedia.org/wiki/Reformation",
      icon: "fa-solid fa-church",
      image: "https://firstamendment.mtsu.edu/wp-content/uploads/sites/2/2023/06/Luther95theses_0.jpg"
    },
    {
      id: "enlightenment",
      era: "Modern History",
      year: 1688,
      date: "c. 1688-1789",
      title: "The Enlightenment",
      location: "Europe",
      description: "An intellectual and philosophical movement that emphasized reason, individualism, and skepticism, challenging traditional authority.",
      link: "https://en.wikipedia.org/wiki/Age_of_Enlightenment",
      icon: "fa-solid fa-lightbulb",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Jean-Jacques_Rousseau_%28painted_portrait%29.jpg/800px-Jean-Jacques_Rousseau_%28painted_portrait%29.jpg"
    },
    {
      id: "industrial-revolution",
      era: "Modern History",
      year: 1760,
      date: "c. 1760 - 1840",
      title: "The Industrial Revolution",
      location: "Great Britain",
      description: "A period of major industrialization that saw the transition to new manufacturing processes, fundamentally changing society.",
      link: "https://en.wikipedia.org/wiki/Industrial_Revolution",
      icon: "fa-solid fa-industry",
      image: "https://res.cloudinary.com/aenetworks/image/upload/c_fill,ar_1.7777777777777777,w_3840,h_2163,g_center/dpr_auto/f_auto/q_auto:eco:sensitive/v1/second_industrial_revolution_gettyimages-51632462-1?_a=BAVAZGDX0"
    },
    {
      id: "american-revolution",
      era: "Modern History",
      year: 1776,
      date: "1776 CE",
      title: "American Declaration of Independence",
      location: "Philadelphia, USA",
      description: "The thirteen American colonies declare independence from Great Britain, leading to the formation of the United States.",
      link: "https://en.wikipedia.org/wiki/United_States_Declaration_of_Independence",
      icon: "fa-solid fa-flag-usa",
      image: "https://cdn.britannica.com/21/143621-159-3EDE9040/Declaration-of-Independence-canvas-rotunda-John-Trumbull-July-4-1776.jpg"
    },
    {
      id: "french-revolution",
      era: "Modern History",
      year: 1789,
      date: "1789 CE",
      title: "The French Revolution",
      location: "Paris, France",
      description: "A period of radical political and societal change in France that ended the monarchy and had a lasting impact on modern history.",
      link: "https://en.wikipedia.org/wiki/French_Revolution",
      icon: "fa-solid fa-torii-gate",
      image: "https://static.wixstatic.com/media/5419df_9d99fd75706848bf88903630a53a7a54~mv2.jpg/v1/fill/w_640,h_424,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/5419df_9d99fd75706848bf88903630a53a7a54~mv2.jpghttps://orion-uploads.openroadmedia.com/md_6780fb194163-napoleon.jpg"
    },
  
    // Contemporary History
    {
      id: "napoleonic-wars",
      era: "Contemporary History",
      year: 1803,
      date: "1803-1815",
      title: "Napoleonic Wars",
      location: "Europe",
      description: "A series of major global conflicts pitting the French Empire and its allies, led by Napoleon I, against a fluctuating array of European powers.",
      link: "https://en.wikipedia.org/wiki/Napoleonic_Wars",
      icon: "fa-solid fa-chess-king",
      image: "https://orion-uploads.openroadmedia.com/md_6780fb194163-napoleon.jpg"
    },
    {
      id: "communist-manifesto",
      era: "Contemporary History",
      year: 1848,
      date: "1848 CE",
      title: "The Communist Manifesto",
      location: "London, UK",
      description: "Karl Marx and Friedrich Engels publish their political pamphlet, which would become one of the world's most influential political documents.",
      link: "https://en.wikipedia.org/wiki/The_Communist_Manifesto",
      icon: "fa-solid fa-book-skull",
      image: "https://m.media-amazon.com/images/I/71O1MLu9evL._UF894,1000_QL80_.jpg"
    },
    {
      id: "ww1",
      era: "Contemporary History",
      year: 1914,
      date: "1914-1918",
      title: "World War I",
      location: "Global",
      description: "Known as the Great War, it was a global conflict that reshaped the political map of Europe and led to unprecedented casualties.",
      link: "https://en.wikipedia.org/wiki/World_War_I",
      icon: "fa-solid fa-helmet-safety",
      image: "https://www.historyhit.com/app/uploads/2020/07/The_Battle_of_the_Somme_film_image1-3.jpg"
    },
    {
      id: "russian-revolution",
      era: "Contemporary History",
      year: 1917,
      date: "1917 CE",
      title: "Russian Revolution",
      location: "Russia",
      description: "A pair of revolutions that dismantled the Tsarist autocracy and led to the rise of the Soviet Union, the world's first communist state.",
      link: "https://en.wikipedia.org/wiki/Russian_Revolution",
      icon: "fa-solid fa-star",
      image: "https://update.lib.berkeley.edu/wp-content/uploads/2017/09/RUSSIANREV_02.jpg"
    },
    {
      id: "ww2",
      era: "Contemporary History",
      year: 1939,
      date: "1939-1945",
      title: "World War II",
      location: "Global",
      description: "The deadliest conflict in human history, involving more than 30 countries and resulting in 70 to 85 million fatalities.",
      link: "https://en.wikipedia.org/wiki/World_War_II",
      icon: "fa-solid fa-plane-bomb",
      image: "https://www.historic-newspapers.com/cdn/shop/articles/WW2-timeline-featured-iage_662e418e-ab05-436e-a8ee-94736a47c32c.jpg?v=1749305962&width=1440"
    },
    {
      id: "moon-landing",
      era: "Contemporary History",
      year: 1969,
      date: "1969",
      title: "Apollo 11 Moon Landing",
      location: "The Moon",
      description: "Neil Armstrong and Buzz Aldrin become the first humans to walk on the Moon, a monumental achievement for science and exploration.",
      link: "https://en.wikipedia.org/wiki/Apollo_11",
      icon: "fa-solid fa-rocket",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Aldrin_Apollo_11_original.jpg/800px-Aldrin_Apollo_11_original.jpg"
    },
    {
      id: "fall-of-berlin-wall",
      era: "Contemporary History",
      year: 1989,
      date: "1989 CE",
      title: "Fall of the Berlin Wall",
      location: "Berlin, Germany",
      description: "The pivotal event that symbolized the end of the Cold War and led to the reunification of Germany.",
      link: "https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall",
      icon: "fa-solid fa-bridge-circle-xmark",
      image: "https://media.cnn.com/api/v1/images/stellar/prod/191107162239-berlin-wall-fall-1.jpg?q=w_3748,h_2457,x_0,y_0,c_fill"
    },
    {
      id: "world-wide-web",
      era: "Contemporary History",
      year: 1991,
      date: "1991",
      title: "The World Wide Web becomes Public",
      location: "Global",
      description: "CERN makes the World Wide Web project public, sparking the digital revolution and fundamentally changing how we access information.",
      link: "https://en.wikipedia.org/wiki/History_of_the_World_Wide_Web",
      icon: "fa-solid fa-globe",
      image: "https://www.firstonline.info/wp-content/uploads/2024/08/www.webp"
    },
    {
      id: "covid-19",
      era: "Contemporary History",
      year: 2020,
      date: "2020 CE",
      title: "COVID-19 Pandemic",
      location: "Global",
      description: "A worldwide pandemic caused by a novel coronavirus that led to global social and economic disruption, lockdowns, and millions of deaths.",
      link: "https://en.wikipedia.org/wiki/COVID-19_pandemic",
      icon: "fa-solid fa-virus-covid",
      image: "https://www.un.org/sites/un2.un.org/files/field/image/1583952355.1997.jpg"
    }
  ];
  